package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AsistenciaDetalle generated by hbm2java
 */
public class AsistenciaDetalleBO implements java.io.Serializable {

	private int idDetalle;
	private AsistenciaBO asistencia;
	private char tipoRegistro;
	private char tipoMarcacion;
	private Date hora;
	private String rutaFoto;

	public AsistenciaDetalleBO() {
	}

	public AsistenciaDetalleBO(int idDetalle, char tipoRegistro,
			char tipoMarcacion, Date hora, String rutaFoto) {
		this.idDetalle = idDetalle;
		this.tipoRegistro = tipoRegistro;
		this.tipoMarcacion = tipoMarcacion;
		this.hora = hora;
		this.rutaFoto = rutaFoto;
	}

	public AsistenciaDetalleBO(int idDetalle, AsistenciaBO asistencia,
			char tipoRegistro, char tipoMarcacion, Date hora, String rutaFoto) {
		this.idDetalle = idDetalle;
		this.asistencia = asistencia;
		this.tipoRegistro = tipoRegistro;
		this.tipoMarcacion = tipoMarcacion;
		this.hora = hora;
		this.rutaFoto = rutaFoto;
	}

	public int getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(int idDetalle) {
		this.idDetalle = idDetalle;
	}

	public AsistenciaBO getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(AsistenciaBO asistencia) {
		this.asistencia = asistencia;
	}

	public char getTipoRegistro() {
		return this.tipoRegistro;
	}

	public void setTipoRegistro(char tipoRegistro) {
		this.tipoRegistro = tipoRegistro;
	}

	public char getTipoMarcacion() {
		return this.tipoMarcacion;
	}

	public void setTipoMarcacion(char tipoMarcacion) {
		this.tipoMarcacion = tipoMarcacion;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getRutaFoto() {
		return this.rutaFoto;
	}

	public void setRutaFoto(String rutaFoto) {
		this.rutaFoto = rutaFoto;
	}

}
