package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class CursoBO implements java.io.Serializable {

	private int idCurso;
	private String coCurso;
	private String nomCurso;
	private int nuCreditos;

	public CursoBO() {
	}

	public CursoBO(int idCurso, String coCurso, String nomCurso, int nuCreditos) {
		this.idCurso = idCurso;
		this.coCurso = coCurso;
		this.nomCurso = nomCurso;
		this.nuCreditos = nuCreditos;
	}
	
	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		this.idCurso = idCurso;
	}

	public String getCoCurso() {
		return this.coCurso;
	}

	public void setCoCurso(String coCurso) {
		this.coCurso = coCurso;
	}

	public String getNomCurso() {
		return this.nomCurso;
	}

	public void setNomCurso(String nomCurso) {
		this.nomCurso = nomCurso;
	}

	public int getNuCreditos() {
		return this.nuCreditos;
	}

	public void setNuCreditos(int nuCreditos) {
		this.nuCreditos = nuCreditos;
	}
}
