package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

/**
 * Foto generated by hbm2java
 */
public class FotoBO implements java.io.Serializable {

	private int idFoto;
	private DocenteBO docente;
	private String nomRuta;
	private char blEstado;

	public FotoBO() {
	}

	public FotoBO(int idFoto, String nomRuta, char blEstado) {
		this.idFoto = idFoto;
		this.nomRuta = nomRuta;
		this.blEstado = blEstado;
	}

	public FotoBO(int idFoto, DocenteBO docente, String nomRuta, char blEstado) {
		this.idFoto = idFoto;
		this.docente = docente;
		this.nomRuta = nomRuta;
		this.blEstado = blEstado;
	}

	public int getIdFoto() {
		return this.idFoto;
	}

	public void setIdFoto(int idFoto) {
		this.idFoto = idFoto;
	}

	public DocenteBO getDocente() {
		return this.docente;
	}

	public void setDocente(DocenteBO docente) {
		this.docente = docente;
	}

	public String getNomRuta() {
		return this.nomRuta;
	}

	public void setNomRuta(String nomRuta) {
		this.nomRuta = nomRuta;
	}

	public char getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(char blEstado) {
		this.blEstado = blEstado;
	}

}
