package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * HorarioCurso generated by hbm2java
 */
public class HorarioCursoBO implements java.io.Serializable {

	private int idHorarioCurso;
	private DocenteBO docente;
	private HorarioBO horario;
	private CursoBO curso;
	private String semestre;
	private String nomGrupo;
	private String nomTipoClase;
	private char estado;

	public HorarioCursoBO() {
	}

	public HorarioCursoBO(int idHorarioCurso, String semestre, String nomGrupo,
			String nomTipoClase, char estado) {
		this.idHorarioCurso = idHorarioCurso;
		this.semestre = semestre;
		this.nomGrupo = nomGrupo;
		this.nomTipoClase = nomTipoClase;
		this.estado = estado;
	}

	public int getIdHorarioCurso() {
		return this.idHorarioCurso;
	}

	public void setIdHorarioCurso(int idHorarioCurso) {
		this.idHorarioCurso = idHorarioCurso;
	}

	public DocenteBO getDocente() {
		return this.docente;
	}

	public void setDocente(DocenteBO docente) {
		this.docente = docente;
	}

	public HorarioBO getHorario() {
		return this.horario;
	}

	public void setHorario(HorarioBO horario) {
		this.horario = horario;
	}

	public CursoBO getCurso() {
		return this.curso;
	}

	public void setCurso(CursoBO curso) {
		this.curso = curso;
	}

	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

	public String getNomGrupo() {
		return this.nomGrupo;
	}

	public void setNomGrupo(String nomGrupo) {
		this.nomGrupo = nomGrupo;
	}

	public String getNomTipoClase() {
		return this.nomTipoClase;
	}

	public void setNomTipoClase(String nomTipoClase) {
		this.nomTipoClase = nomTipoClase;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
