package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class HorarioBO implements java.io.Serializable {

	private String nomCurso;
	private String nomDia;
	private String nomDocente;
	private String hoInicio;
	private String hoFin;
	private String nomGrupo;
	private String nomTipoClase;

	public HorarioBO() {
	}

	public String getNomCurso() {
		return nomCurso;
	}

	public void setNomCurso(String nomCurso) {
		this.nomCurso = nomCurso;
	}

	public String getNomDia() {
		return nomDia;
	}

	public void setNomDia(String nomDia) {
		this.nomDia = nomDia;
	}

	public String getNomDocente() {
		return nomDocente;
	}

	public void setNomDocente(String nomDocente) {
		this.nomDocente = nomDocente;
	}

	public String getHoInicio() {
		return hoInicio;
	}

	public void setHoInicio(String hoInicio) {
		this.hoInicio = hoInicio;
	}

	public String getHoFin() {
		return hoFin;
	}

	public void setHoFin(String hoFin) {
		this.hoFin = hoFin;
	}

	public String getNomGrupo() {
		return nomGrupo;
	}

	public void setNomGrupo(String nomGrupo) {
		this.nomGrupo = nomGrupo;
	}

	public String getNomTipoClase() {
		return nomTipoClase;
	}

	public void setNomTipoClase(String nomTipoClase) {
		this.nomTipoClase = nomTipoClase;
	}

	@Override
	public String toString() {
		return "HorarioBO{" +
				"nomCurso='" + nomCurso + '\'' +
				", nomDia='" + nomDia + '\'' +
				", nomDocente='" + nomDocente + '\'' +
				", hoInicio='" + hoInicio + '\'' +
				", hoFin='" + hoFin + '\'' +
				", nomGrupo='" + nomGrupo + '\'' +
				", nomTipoClase='" + nomTipoClase + '\'' +
				'}';
	}
}
