package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class HorarioBO implements java.io.Serializable {

	private int idHorario;
	private String nomDia;
	private Date hoInicio;
	private Date hoFin;

	public HorarioBO() {
	}

	public HorarioBO(int idHorario, String nomDia, Date hoInicio, Date hoFin) {
		this.idHorario = idHorario;
		this.nomDia = nomDia;
		this.hoInicio = hoInicio;
		this.hoFin = hoFin;
	}

	public int getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(int idHorario) {
		this.idHorario = idHorario;
	}

	public String getNomDia() {
		return this.nomDia;
	}

	public void setNomDia(String nomDia) {
		this.nomDia = nomDia;
	}

	public Date getHoInicio() {
		return this.hoInicio;
	}

	public void setHoInicio(Date hoInicio) {
		this.hoInicio = hoInicio;
	}

	public Date getHoFin() {
		return this.hoFin;
	}

	public void setHoFin(Date hoFin) {
		this.hoFin = hoFin;
	}
}
