package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

/**
 * Usuario generated by hbm2java
 */
public class UsuarioBO implements java.io.Serializable {

	private int idUsuario;
	private PersonalBO personal;
	private String nomUsuario;
	private String clave;

	public UsuarioBO() {
	}

	public UsuarioBO(int idUsuario, String nomUsuario, String clave) {
		this.idUsuario = idUsuario;
		this.nomUsuario = nomUsuario;
		this.clave = clave;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public PersonalBO getPersonal() {
		return this.personal;
	}

	public void setPersonal(PersonalBO personal) {
		this.personal = personal;
	}

	public String getNomUsuario() {
		return this.nomUsuario;
	}

	public void setNomUsuario(String nomUsuario) {
		this.nomUsuario = nomUsuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}
}
