package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioRolId generated by hbm2java
 */
public class UsuarioRolIdBO implements java.io.Serializable {

	private int idUsuario;
	private int idRol;

	public UsuarioRolIdBO() {
	}

	public UsuarioRolIdBO(int idUsuario, int idRol) {
		this.idUsuario = idUsuario;
		this.idRol = idRol;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioRolIdBO))
			return false;
		UsuarioRolIdBO castOther = (UsuarioRolIdBO) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdRol() == castOther.getIdRol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdRol();
		return result;
	}

}
