package pe.edu.sistemas.asidoc.bo;

// Generated 23-nov-2016 14:14:44 by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRolBO implements java.io.Serializable {

	private UsuarioRolIdBO id;
	private RolBO rol;
	private UsuarioBO usuario;

	public UsuarioRolBO() {
	}

	public UsuarioRolBO(UsuarioRolIdBO id, RolBO rol, UsuarioBO usuario) {
		this.id = id;
		this.rol = rol;
		this.usuario = usuario;
	}

	public UsuarioRolIdBO getId() {
		return this.id;
	}

	public void setId(UsuarioRolIdBO id) {
		this.id = id;
	}

	public RolBO getRol() {
		return this.rol;
	}

	public void setRol(RolBO rol) {
		this.rol = rol;
	}

	public UsuarioBO getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioBO usuario) {
		this.usuario = usuario;
	}

}
