package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "asistencia", schema = "dbasidoc")
public class Asistencia implements java.io.Serializable {

	private int idAsistencia;
	private HorarioCurso horarioCurso;
	private String tipoAsistencia;
	private Date feRegistro;
	private char validacion;

	public Asistencia() {
	}

	public Asistencia(int idAsistencia, HorarioCurso horarioCurso,
			String tipoAsistencia, Date feRegistro, char validacion) {
		this.idAsistencia = idAsistencia;
		this.horarioCurso = horarioCurso;
		this.tipoAsistencia = tipoAsistencia;
		this.feRegistro = feRegistro;
		this.validacion = validacion;
	}

	@Id
	@Column(name = "id_asistencia", unique = true, nullable = false)
	public int getIdAsistencia() {
		return this.idAsistencia;
	}

	public void setIdAsistencia(int idAsistencia) {
		this.idAsistencia = idAsistencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_horario_curso", nullable = false)
	public HorarioCurso getHorarioCurso() {
		return this.horarioCurso;
	}

	public void setHorarioCurso(HorarioCurso horarioCurso) {
		this.horarioCurso = horarioCurso;
	}

	@Column(name = "tipo_asistencia", nullable = false, length = 3)
	public String getTipoAsistencia() {
		return this.tipoAsistencia;
	}

	public void setTipoAsistencia(String tipoAsistencia) {
		this.tipoAsistencia = tipoAsistencia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fe_registro", nullable = false, length = 13)
	public Date getFeRegistro() {
		return this.feRegistro;
	}

	public void setFeRegistro(Date feRegistro) {
		this.feRegistro = feRegistro;
	}

	@Column(name = "validacion", nullable = false, length = 1)
	public char getValidacion() {
		return this.validacion;
	}

	public void setValidacion(char validacion) {
		this.validacion = validacion;
	}
}
