package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AsistenciaDetalle generated by hbm2java
 */
@Entity
@Table(name = "asistencia_detalle", schema = "dbasidoc")
public class AsistenciaDetalle implements java.io.Serializable {

	private int idDetalle;
	private Asistencia asistencia;
	private char tipoRegistro;
	private char tipoMarcacion;
	private Date hora;
	private String rutaFoto;

	public AsistenciaDetalle() {
	}

	public AsistenciaDetalle(int idDetalle, char tipoRegistro,
			char tipoMarcacion, Date hora, String rutaFoto) {
		this.idDetalle = idDetalle;
		this.tipoRegistro = tipoRegistro;
		this.tipoMarcacion = tipoMarcacion;
		this.hora = hora;
		this.rutaFoto = rutaFoto;
	}

	public AsistenciaDetalle(int idDetalle, Asistencia asistencia,
			char tipoRegistro, char tipoMarcacion, Date hora, String rutaFoto) {
		this.idDetalle = idDetalle;
		this.asistencia = asistencia;
		this.tipoRegistro = tipoRegistro;
		this.tipoMarcacion = tipoMarcacion;
		this.hora = hora;
		this.rutaFoto = rutaFoto;
	}

	@Id
	@Column(name = "id_detalle", unique = true, nullable = false)
	public int getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(int idDetalle) {
		this.idDetalle = idDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asistencia")
	public Asistencia getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Asistencia asistencia) {
		this.asistencia = asistencia;
	}

	@Column(name = "tipo_registro", nullable = false, length = 1)
	public char getTipoRegistro() {
		return this.tipoRegistro;
	}

	public void setTipoRegistro(char tipoRegistro) {
		this.tipoRegistro = tipoRegistro;
	}

	@Column(name = "tipo_marcacion", nullable = false, length = 1)
	public char getTipoMarcacion() {
		return this.tipoMarcacion;
	}

	public void setTipoMarcacion(char tipoMarcacion) {
		this.tipoMarcacion = tipoMarcacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora", nullable = false, length = 29)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "ruta_foto", nullable = false, length = 256)
	public String getRutaFoto() {
		return this.rutaFoto;
	}

	public void setRutaFoto(String rutaFoto) {
		this.rutaFoto = rutaFoto;
	}

}
