package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso")
public class Curso implements java.io.Serializable {

	private int idCurso;
	private String coCurso;
	private String nomCurso;
	private int nuCreditos;
	
	public Curso() {
	}

	public Curso(int idCurso, String coCurso, String nomCurso, int nuCreditos) {
		this.idCurso = idCurso;
		this.coCurso = coCurso;
		this.nomCurso = nomCurso;
		this.nuCreditos = nuCreditos;
	}

	@Id
	@Column(name = "id_curso", unique = true, nullable = false)
	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		this.idCurso = idCurso;
	}

	@Column(name = "co_curso", nullable = false, length = 15)
	public String getCoCurso() {
		return this.coCurso;
	}

	public void setCoCurso(String coCurso) {
		this.coCurso = coCurso;
	}

	@Column(name = "nom_curso", nullable = false, length = 40)
	public String getNomCurso() {
		return this.nomCurso;
	}

	public void setNomCurso(String nomCurso) {
		this.nomCurso = nomCurso;
	}

	@Column(name = "nu_creditos", nullable = false)
	public int getNuCreditos() {
		return this.nuCreditos;
	}

	public void setNuCreditos(int nuCreditos) {
		this.nuCreditos = nuCreditos;
	}
}
