package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", schema = "dbasidoc")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private String codDocente;
	private String numDni;
	private String nomDocente;
	private String apePaterno;
	private String apeMaterno;
	private Date feNacimiento;
	private String email;

	public Docente() {
	}

	public Docente(int idDocente, String codDocente, String numDni,
			String nomDocente, String apePaterno, String apeMaterno,
			Date feNacimiento, String email) {
		this.idDocente = idDocente;
		this.codDocente = codDocente;
		this.numDni = numDni;
		this.nomDocente = nomDocente;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.feNacimiento = feNacimiento;
		this.email = email;
	}
	
	@Id
	@Column(name = "id_docente", unique = true, nullable = false)
	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@Column(name = "cod_docente", nullable = false, length = 15)
	public String getCodDocente() {
		return this.codDocente;
	}

	public void setCodDocente(String codDocente) {
		this.codDocente = codDocente;
	}

	@Column(name = "num_dni", nullable = false, length = 15)
	public String getNumDni() {
		return this.numDni;
	}

	public void setNumDni(String numDni) {
		this.numDni = numDni;
	}

	@Column(name = "nom_docente", nullable = false, length = 35)
	public String getNomDocente() {
		return this.nomDocente;
	}

	public void setNomDocente(String nomDocente) {
		this.nomDocente = nomDocente;
	}

	@Column(name = "ape_paterno", nullable = false, length = 35)
	public String getApePaterno() {
		return this.apePaterno;
	}

	public void setApePaterno(String apePaterno) {
		this.apePaterno = apePaterno;
	}

	@Column(name = "ape_materno", nullable = false, length = 35)
	public String getApeMaterno() {
		return this.apeMaterno;
	}

	public void setApeMaterno(String apeMaterno) {
		this.apeMaterno = apeMaterno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fe_nacimiento", nullable = false, length = 13)
	public Date getFeNacimiento() {
		return this.feNacimiento;
	}

	public void setFeNacimiento(Date feNacimiento) {
		this.feNacimiento = feNacimiento;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}
