package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HorarioCurso generated by hbm2java
 */
@Entity
@Table(name = "horario_curso", schema = "dbasidoc")
public class HorarioCurso implements java.io.Serializable {

	private int idHorarioCurso;
	private Docente docente;
	private Horario horario;
	private Curso curso;
	private String semestre;
	private String nomGrupo;
	private String nomTipoClase;
	private char estado;
	public HorarioCurso() {
	}

	public HorarioCurso(int idHorarioCurso, String semestre, String nomGrupo,
			String nomTipoClase, char estado) {
		this.idHorarioCurso = idHorarioCurso;
		this.semestre = semestre;
		this.nomGrupo = nomGrupo;
		this.nomTipoClase = nomTipoClase;
		this.estado = estado;
	}
	
	@Id
	@Column(name = "id_horario_curso", unique = true, nullable = false)
	public int getIdHorarioCurso() {
		return this.idHorarioCurso;
	}

	public void setIdHorarioCurso(int idHorarioCurso) {
		this.idHorarioCurso = idHorarioCurso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente")
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_horario")
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_curso")
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Column(name = "semestre", nullable = false, length = 20)
	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

	@Column(name = "nom_grupo", nullable = false, length = 5)
	public String getNomGrupo() {
		return this.nomGrupo;
	}

	public void setNomGrupo(String nomGrupo) {
		this.nomGrupo = nomGrupo;
	}

	@Column(name = "nom_tipo_clase", nullable = false, length = 5)
	public String getNomTipoClase() {
		return this.nomTipoClase;
	}

	public void setNomTipoClase(String nomTipoClase) {
		this.nomTipoClase = nomTipoClase;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}
}
