package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name = "personal")
public class Personal implements java.io.Serializable {

	private int idPersonal;
	private String nombre;
	private String apellido;
	private String correo;

	public Personal() {
	}

	public Personal(int idPersonal, String nombre, String apellido,
			String correo) {
		this.idPersonal = idPersonal;
		this.nombre = nombre;
		this.apellido = apellido;
		this.correo = correo;
	}
	
	@Id
	@Column(name = "id_personal", unique = true, nullable = false)
	public int getIdPersonal() {
		return this.idPersonal;
	}

	public void setIdPersonal(int idPersonal) {
		this.idPersonal = idPersonal;
	}

	@Column(name = "nombre", nullable = false, length = 35)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 35)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "correo", nullable = false, length = 64)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}
}
