package pe.edu.sistemas.asidoc.dao.dominio;

// Generated 26-nov-2016 10:22:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioRolId generated by hbm2java
 */
@Embeddable
public class UsuarioRolId implements java.io.Serializable {

	private int idUsuario;
	private int idRol;

	public UsuarioRolId() {
	}

	public UsuarioRolId(int idUsuario, int idRol) {
		this.idUsuario = idUsuario;
		this.idRol = idRol;
	}

	@Column(name = "id_usuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_rol", nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioRolId))
			return false;
		UsuarioRolId castOther = (UsuarioRolId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdRol() == castOther.getIdRol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdRol();
		return result;
	}

}
